### ISSUE TITLE
`post_update` commands always run even with `dolly install`

### ISSUE THREAD

**Issue by kiesel** [xp-forge/dolly#17]
The `post_update` commands will always be run, even when I run `dolly install` which should only operate on new, not yet present repositories.

I'd expect the commands only be run for freshly checked out repos in that mode.

**Comment by lluchs** [comment]
This is fixed now for repository-level `post_update` commands. Those at the project level will still run every time.

**Comment by kiesel** [comment]
As #22 introduced the `--no-post-update` flags that can be used in this case, too, I'll close this issue.
