### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [xp-forge/dolly#19]
What would be the license for this fine piece of code?

**Comment by kiesel** [comment]
Oops, we weren't aware, we've forgotten to name a license. We usually provide our code as-is with a BSD/MIT-style license, so that's what I'll add here, too.

**Comment by kiesel** [comment]
Added in b065d7a3d24ec947b6a627b018e5d3c07013ed54

**Comment by pombredanne** [comment]
Thanks!
