### ISSUE TITLE
Post-update command should be run in a checkouts directory, by default

### ISSUE THREAD

**Issue by kiesel** [xp-forge/dolly#20]
When forking the `post_update` command for a repo, dolly should fork the process inside the checkout directory.

Usually, one wants to do project-related things, so most commands now look like `cd /path/to/repo && make something`.

**Comment by lluchs** [comment]
This is already the case. Only project-level post_update commands don't have a proper working directory.

**Comment by lluchs** [comment]
I updated the project-level post_update to run inside the dolly root directory. This allows using relative paths within the command to navigate to one of the `tree` directories used in the project.
