### ISSUE TITLE
Add "unknown" command

### ISSUE THREAD

**Issue by kiesel** [xp-forge/dolly#23]
Add a `unknown` subcommand that does the following: iterate over the given root directory and print out directory elements (that are git/svn repositories) that are not known to dolly.

This should find unconfigured / manually checked out repos in your tree.

PS: Maybe you can come up with a more suitable command name:)

**Comment by iigorr** [comment]
alternative name: discover, untracked

**Comment by kiesel** [comment]
untracked sounds good :)
